"""Add is_available to Product model

Revision ID: 0325eb5d92bf
Revises: 7e2eff1ad37c
Create Date: 2025-10-31 18:14:50.371185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0325eb5d92bf'
down_revision: Union[str, None] = '7e2eff1ad37c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_available', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_available')
    # ### end Alembic commands ###
