"""add address and payment method to order

Revision ID: 5d094c5a2532
Revises: c073be2b2dee
Create Date: 2025-10-20 19:40:38.798138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d094c5a2532'
down_revision: Union[str, None] = 'c073be2b2dee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_items', ['id'])
    op.add_column('orders', sa.Column('address', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('payment_method', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'orders', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_column('orders', 'payment_method')
    op.drop_column('orders', 'address')
    op.drop_constraint(None, 'order_items', type_='unique')
    # ### end Alembic commands ###
