"""add thumbnail to category

Revision ID: 86f41521a4e9
Revises: 5d094c5a2532
Create Date: 2025-10-20 20:27:56.089049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86f41521a4e9'
down_revision: Union[str, None] = '5d094c5a2532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('thumbnail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'thumbnail')
    # ### end Alembic commands ###
