"""Add Order and OrderItem models

Revision ID: c073be2b2dee
Revises: 24af09e935cb
Create Date: 2025-10-15 11:09:23.519013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c073be2b2dee'
down_revision: Union[str, None] = '24af09e935cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.alter_column('cart_items', 'subtotal',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'cart_items', ['id'])
    op.alter_column('carts', 'total_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_unique_constraint(None, 'carts', ['id'])
    op.create_unique_constraint(None, 'categories', ['id'])
    op.alter_column('products', 'discount_percentage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'rating',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('products', 'images',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False)
    op.create_unique_constraint(None, 'products', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'products', type_='unique')
    op.alter_column('products', 'images',
               existing_type=sa.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=False)
    op.alter_column('products', 'rating',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('products', 'discount_percentage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'categories', type_='unique')
    op.drop_constraint(None, 'carts', type_='unique')
    op.alter_column('carts', 'total_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_constraint(None, 'cart_items', type_='unique')
    op.alter_column('cart_items', 'subtotal',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
