"""Add description to Category model

Revision ID: c9a0546ba682
Revises: cef7c0fc32ae
Create Date: 2025-10-23 16:24:33.047556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a0546ba682'
down_revision: Union[str, None] = 'cef7c0fc32ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('description', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'product_images', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product_images', type_='unique')
    op.drop_column('categories', 'description')
    # ### end Alembic commands ###
